# spring.config.import=optional:classpath:.env
server.port=8081
# ========= Application =========
spring.application.name=ProductClientService
server.address=0.0.0.0

# ========= Database =========
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ========= Redis (local network) =========
spring.data.redis.host=192.168.1.113
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=false

# ========= JWT =========
jwt.private.key.path=classpath:keys/private_key.pem
jwt.public.key.path=classpath:keys/public_key.pem
jwt.expiration.in.millis=9000000
jwt.refresh.expiration.days=7

# ========= Feign Clients =========
feign.client.orderpaymentnotification.url=http://localhost:8081
feign.client.delivery_inventory_client.url=http://localhost:8082

# ========= Google API =========
google.api.key=${GOOGLE_API_KEY}

# ========= Elasticsearch (local network) =========
elasticsearch.url=http://192.168.1.113:9200

# ========= AWS S3 =========
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}
cloud.aws.s3.bucket-name=${AWS_S3_BUCKET}

# ========= Internal Service API Key =========
internal.api.key=${INTERNAL_API_KEY}

# ========= Kafka (local network) =========
kafka.bootstrap-servers=192.168.1.113:9092

# ========= Cloudinary =========
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

# ========= Aadhaar Verification =========
aadhaar.api.endpoint=${AADHAAR_API_ENDPOINT:https://api.example.com/aadhaar}
aadhaar.api.key=tgghjjmmhhh
aadhaar.verification.bypass=true
