name: CI/CD for ProductClientService

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/productclientservice:latest .

      # Push Docker image
      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/productclientservice:latest

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy productclientservice
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/productclientservice:latest
          --platform managed
          --region asia-south1
          --allow-unauthenticated
